REM Comment any files that should not be executed.
REM Host=127.0.0.1	Port=3306	User=root	Pwd=<empty>	Database=core

REM Tables: These will replace current tables with the new table structures as stored in these files
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_accommodation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_accommodation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_account.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_account.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_asset.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_asset.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_attendance.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_batch.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_contact.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_contact.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_country.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_date.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_event.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_event.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_gender.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_global.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_group.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_group.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_hospitality.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_identity.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_journal.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_journal.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_language.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_location.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_location.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_lodging.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_management.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_membership.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_multimedia.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_multimedia.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_nationality.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_organisation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_party.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_party.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_period.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_period.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_person.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_person.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_photo.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_programme.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_programme.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_registry.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_requirement.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_role.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_role.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_salutation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_skill_level.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_skill.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_time.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_transportation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_kind_of_transportation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\tbl_whereabouts.sql"

REM Views: These will replace current views with the new views as stored in these files
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\accommodation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_accommodation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\account.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_account.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\asset.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_asset.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\attendance.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\batch.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\contact.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_contact.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\country.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\date.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\event.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_event.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\gender.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\global.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\group.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_group.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\hospitality.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\identity.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\journal.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_journal.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\language.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\location.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_location.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\lodging.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\management.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\membership.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\multimedia.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_multimedia.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\nationality.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\organisation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\party.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_party.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\period.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_period.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\person.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_person.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\photo.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\programme.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_programme.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\registry.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\requirement.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\role.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_role.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\salutation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\skill_level.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\skill.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\time.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\transportation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\kind_of_transportation.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\views\whereabouts.sql"

REM Data: These will replace current data in the tables with new data as stored in these files
REM Only to be used with empty tables and/or lookup tables e.g. countries.
REM Be aware that keys will be assigned to the next increment (hence ids may change value!)

mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_country_data.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_gender_data.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_group_data.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_nationality_data.sql"
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_salutation_data.sql"

REM Data: Samples !!! .... do not use in a production database
mysql --host=127.0.0.1 --port=3306 --user=root --database=core < "c:\sql\core\tables\data\tbl_person_data.sql"